### ISSUE TITLE
EPIC: compliance tasks for gns pilot

### ISSUE THREAD

**Issue by rahearn** [GSA/public-benefits-studio#114]
Scope of this epic: tasks in support of a potential 90-day LATO

- [x] review LATO process
- [x] https://github.com/18F/notifications-api/issues/24
- [x] https://github.com/18F/notifications-admin/issues/29
- [x] #145
- [x] https://github.com/GSA/notifications-api/issues/31
- [x] https://github.com/GSA/notifications-admin/issues/32
- [x] fork compliance-template
- [x] https://github.com/GSA/notifications-admin/issues/33
- [x] https://github.com/GSA/notifications-api/issues/32

**Comment by rahearn** [comment]
API security scans: https://github.com/18F/notifications-api/issues/24

**Comment by rahearn** [comment]
compliance docs will be located at https://github.com/GSA/us-notify-compliance

**Comment by rahearn** [comment]
We will not be getting a 90-day LATO, due to PII concerns. Focusing on the 1-year LATO.
